server:
  port: 3000

db:
  host: 'db-postgres-volarium-space-do-user-8476294-0.b.db.ondigitalocean.com'
  username: 'doadmin'
  password: 'du8rrndnuqxikpsw'
  synchronize: false

jwt:
  secret: '$2b$10$L/7Xb78TQnCNYijdKl5T7e'

